version: "3.8"

services:
  event-ingestor:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: event-ingestor
    ports:
      - "5245:5245"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    restart: unless-stopped
