{
 "title": "Monitoreo Urbano (eventos - alertas) - 2",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "event_type",
    "label": "Tipo Evento",
    "query": "label_values(urbanevents_events_received_total, event_type)"
   },
   {
    "name": "location",
    "label": "Localización",
    "query": "label_values(urbanevents_events_received_total, location)"
   },
   {
    "name": "alert_type",
    "label": "Tipo Alerta",
    "query": {
     "query": "label_values(urbanevents_alerts_generated_total,alert_type)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Mapa de calor por zona por Evento ",
   "type": "heatmap",
   "description": "Visualización de densidad de eventos por tipo y zona. Permite identificar picos de actividad urbana en tiempo real.",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by(event_type, location) (\r\n  urbanevents_events_received_total{\r\n    event_type=~\"$event_type\",\r\n    location=~\"$location\"\r\n  }\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cronología por tipo de alerta",
   "type": "timeseries",
   "description": "Este panel muestra la evolución temporal de alertas urbanas por tipo, permitiendo identificar picos críticos y patrones de comportamiento en distintas zonas.",
   "gridPos": { "h": 7, "w": 12, "x": 11, "y": 0 },
   "targets": [
    {
     "expr": "sum by(alert_type) (\r\n  rate(urbanevents_alerts_generated_total{alert_type=~\"$alert_type\", location=~\"$location\"}[1m])\r\n)\r\n"
    }
   ]
  },
  {
   "title": "Tabla de alertas activas",
   "type": "table",
   "gridPos": { "h": 5, "w": 23, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "topk(10, urbanevents_alerts_generated_total{alert_type=~\"$alert_type\", location=~\"$location\"})"
    }
   ]
  },
  {
   "title": "Cluster Health Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "elasticsearch_cluster_health_status{color!=\"green\"} > 0"
    }
   ]
  }
 ]
}