{
 "title": "PROYECTO ARQUI DASHBOARD",
 "time": { "from": "2025-10-24T18:33:37.763Z", "to": "2025-10-31T07:54:43.531Z" },
 "panels": [
  {
   "title": "Total Eventos Recibidos",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(urbanevents_events_received_total offset 1y)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "MAPA DE CALOR",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum by (zone, event_type) (urbanevents_events_received_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "TABLA DE ALERTAS ACTIVAS",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "topk(10, urbanevents_alerts_generated_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": " Eventos por Minuto por Tipo de Evento",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum by (event_type) (rate(urbanevents_events_received_total[1m])) * 60",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Mapa de Calor por Zona",
   "type": "bargauge",
   "description": "Intensidad de eventos por zona geográfica y tipo de sensor",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (zone, event_type) (\r\n  rate(urbanevents_events_received_total[5m])\r\n)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}