global:
  scrape_interval: 5s  # Cada cuánto Prometheus recopila métricas

scrape_configs:
  # Prometheus se monitorea a sí mismo
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  # Event Ingestor (puerto 5245, tu microservicio .NET principal)
  - job_name: "event_ingestor"
    static_configs:
      - targets: ["event-ingestor:5245"]

  # Correlator (puerto 5246 — usa KestrelMetricServer)
  - job_name: "correlator"
    static_configs:
      - targets: ["correlator:5246"]

  # PostgreSQL Exporter 
  - job_name: "postgres_exporter"
    static_configs:
      - targets: ["postgres-exporter:9187"]

  # Redis Exporter
  - job_name: "redis_exporter"
    static_configs:
      - targets: ["redis-exporter:9121"]
